name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: CI
    uses: mtfields/reusable-workflows/.github/workflows/reusable-build.yml@master
    with:
      dotnet_version: 9.0.x